### PR TITLE
Run longhaul regular against the release branch

### PR DESCRIPTION
**Pull request by tanvigour**
Signed-off-by: tanvigour <tanvi.gour@gmail.com>

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #4827

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by tanvigour** [comment]
@halspang :Please review this when you get a chance, thanks

**Comment by halspang** [comment]
Doesn't this defeat the purpose of the nightly longhaul? I thought we wanted it on master so we could find issues with it before we got to the release time.

**Comment by tanvigour** [comment]
> Doesn't this defeat the purpose of the nightly longhaul? I thought we wanted it on master so we could find issues with it before we got to the release time.

We do have to manually run this against release branch as well to get coverage for release branch during release, and so I thought it would be nice to have that qualification as well. Although this change would run against all branches and maybe we should have it tied to only the new release branch per release? what do you think?

**Comment by halspang** [comment]
During the release we update the regular longhauls to be on the new release while the nightly's tend to stay on master. If you wanted to update the standard longhaul to go off of the release branch (so it updates automatically when we have a new release) I think that'd be a good change. I think the nightly run should be on master though.

**Comment by tanvigour** [comment]
@halspang : Please review when you get a chance, Thanks!

**Pull request closed without merging**
