### PR TITLE
Terraform GCP to Github Actions WIF

### PR DESCRIPTION
**Pull request by robertojrojas**
# Description

This sets up the [Workload Identity Federation](https://cloud.google.com/iam/docs/workload-identity-federation) in the Components Contrib Github Actions Workflow for the Conformance and Certification Tests.

## Issue reference

PR is part of: [#_2651_](https://github.com/dapr/components-contrib/issues/2651)

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by berndverst** [comment]
Why not include in this contrib instead?

FYI @ItalyPaleAle

**Comment by robertojrojas** [comment]
@berndverst @ItalyPaleAle I had quick conversation with other Dapr folks and they mentioned this repo to store Infrastructure related code. It's a one time execution type of code and I've already applied it to the Dapr GCP project `dapr-tests`. I'm happy to move to contrib if it makes more sense to host in there.

**Comment by robertojrojas** [comment]
Moving this PR to https://github.com/dapr/components-contrib

**Comment by ItalyPaleAle** [comment]
Thanks @robertojrojas , I agree with @berndverst  on this.

This repo is primarily for the long-haul test infra (and we may argue this is not the best place for that code either? - that's a separate story)

Since your infrastructure has a single consumer and that is in components-contrib, it is simpler to have the code there, so when we need to make changes in the future we can work in a single place.

**Pull request closed without merging**
